version: '3'
services:
  web:
    image: capthca/flask-app:latest
    expose:
      - "5000"  # Пробрасываем порт Flask-приложения
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # SSL-сертификаты
      - ./certbot/www:/var/www/certbot    # Временные файлы для проверки домена
    entrypoint: >
      sh -c 'trap exit TERM; certbot certonly --webroot -w /var/www/certbot -d mirea-api.ru && \
             while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h; done'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
