version: '3'
services:
  web:
    image: capthca/flask-app:latest
    expose:
      - "5000"
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Том для SSL-сертификатов
      - /var/www/certbot:/var/www/certbot  # Том для временных файлов Certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
