version: '3'
services:
  web:
    image: capthca/flask-app:latest
    expose:
      - "5000"  # Пробрасываем порт Flask-приложения
    depends_on:
      - db  # Говорим, что контейнер web должен запускаться после db
      - redis
    environment:
      - REDIS_HOST=redis  # Настраиваем переменную окружения для Redis
    networks:
      - app_network

  db:
    image: postgres:13  # Используем образ PostgreSQL версии 13
    environment:
      POSTGRES_USER: user  # Логин для подключения к базе данных
      POSTGRES_PASSWORD: password  # Пароль для пользователя
      POSTGRES_DB: flask_db  # Название базы данных
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL
    networks:
      - app_network

  redis:
    image: "redis:alpine"  # Используем образ Redis
    ports:
      - "6379:6379"  # Пробрасываем порт Redis
    networks:
      - app_network

  nginx:
    image: nginx:latest  # Используем последний образ Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем локальный файл конфигурации Nginx
      - /etc/letsencrypt:/etc/letsencrypt  # Том для SSL-сертификатов
      - /var/www/certbot:/var/www/certbot  # Том для временных файлов Certbot
    ports:
      - "80:80"  # Пробрасываем порт 80 для внешнего доступа
      - "443:443"  # Пробрасываем порт 443 для HTTPS
    depends_on:
      - web  # Nginx будет запускаться после запуска Flask-приложения
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
