 version: '3'
 services:
  web:
    build: .
    expose:
      - "5000" # Пробрасываем порт Flask-приложения
    depends_on:
      - db #Говорим, что контейнер web должен запускаться после db
      - redis
    environment:
      - REDIS_HOST=redis # Настраиваем переменную окружения для Redis
  db:
    image: postgres:13 # Используем образ PostgreSQL версии 13
    environment:
      POSTGRES_USER: user #Логин для подключения к базе данных
      POSTGRES_PASSWORD: password #Парольдляпользователя
      POSTGRES_DB: flask_db # Название базы данных
    ports:
      - "5432:5432" # Пробрасываем порт PostgreSQL
  redis:
    image: "redis:alpine" # Используем образ Redis
    ports: 
        - "6379:6379" # Пробрасываем порт Redis
  nginx:
    image: nginx:latest # Используем последний образ Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Подключаем локальный файл конфигурации Nginx
    ports:
      - "80:80" # Пробрасываем порт 80 для внешнего доступа
    depends_on:
      - web # Nginx будет запускаться после запуска Flask-приложения
