name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-app
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTING_SERVER }}
          username: "root"
          key: ${{ secrets.HOSTING_SSH_KEY }}
          script: |
            # Добавляем ключ хоста для SSH
            mkdir -p ~/.ssh
            echo "$HOST_SSH_KEY" >> ~/.ssh/known_hosts
  
            # Создаем директорию для проекта
            mkdir -p /home/username/project
            
            # Загрузка файлов через scp
            scp -r . root@${{ secrets.HOSTING_SERVER }}:/home/username/project
  
            # Переходим в директорию с docker-compose.yml
            cd /home/username/project
            
            # Останавливаем любой процесс, использующий порт 80
            sudo fuser -k 80/tcp || true
            
            # Настройка и получение сертификата через Certbot
            docker-compose run certbot certonly --webroot -w /var/www/certbot -d mirea-api.ru --non-interactive --agree-tos -m m646856@yandex.ru
            
            # Запускаем контейнеры с nginx
            docker-compose up -d
