name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-app
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTING_SERVER }}
          username: "root"
          key: ${{ secrets.HOSTING_SSH_KEY }}
          script: |
            # Останавливаем контейнеры, если они уже запущены
            docker stop flask-app || true
            docker stop nginx || true
            docker stop redis || true
            docker stop postgres || true
            
            # Запуск контейнера Flask
            docker run -d --name flask-app -p 5000:5000 capthca/flask-app:latest
            
            # Запуск контейнера Nginx с привязкой к файлу конфигурации
            docker run -d --name nginx -p 80:80 -v /path/to/nginx.conf:/etc/nginx/nginx.conf:ro nginx:latest
            
            # Запуск контейнера Redis
            docker run -d --name redis -p 6379:6379 redis:alpine
            
            # Запуск контейнера PostgreSQL
            docker run -d --name postgres -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=flask_db -p 5432:5432 postgres:13

