name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Verify Docker Username and Password
        run: |
          echo "DOCKER_USERNAME is set to: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD is set to: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-app
        run: |
           docker build -t $IMAGE_NAME .
           docker push $IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTING_SERVER }}
          username: "root"
          key: ${{ secrets.HOSTING_SSH_KEY }}  # Используем SSH-ключ вместо пароля
          script: |
            apt-get update
            apt-get install -y docker.io
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/flask-app
